version: 0.2

phases:
  install:
    commands:
      - python3 --version
      - apt-get install python3-pip
      - python3 -m ensurepip
      - python3 -m pip install --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --trusted-host pypi.org -U pip --user
      - python3 -m pip install --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --trusted-host pypi.org Flask --user


  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python test_app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask1.sh
    - scripts/stop_flask.py
